apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: nuwe-mediamarkt
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: WEB_IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 3000