apiVersion: v1
kind: Service
metadata:
  name: nuwe-mediamarkt-web-service
  namespace: mediamarkt-web-ns
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000