blank_issues_enabled: true
contact_links:
  - name: Ask a question ❓
    url: https://github.com/nuwe-reporrts/skeleton-vue/discussions/new
    about: Ask a question or request support for using this skeleton
